export enum APIErrorType {
  USER_CANCELLED_REQUEST = 'USER_CANCELLED_REQUEST',
  NETWORK_ERROR = 'NETWORK_ERROR',
  CONNECTION_ERROR = 'CONNECTION_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  CLIENT_ERROR = 'CLIENT_ERROR',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
}

export enum APIErrorCategory {
  VALIDATION = 'VALIDATION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  SERVER = 'SERVER',
  NETWORK = 'NETWORK',
  TIMEOUT = 'TIMEOUT',
  CANCEL = 'CANCEL',
  UNKNOWN = 'UNKNOWN'
}
